import Cake1 from "../../assets/Rectangle 27.png";

export const products = [
    // Chocolate cakes
    {
        title: "Chocolate Cake 01",
        ctg: "Chocolate",
        price: 250000,
        img: Cake1,
        rating: 4.8,
        reviews: 150,
    },
    {
        title: "Chocolate Cake 02",
        ctg: "Chocolate",
        price: 270000,
        img: Cake1,
        rating: 4.5,
        reviews: 120,
    },
    {
        title: "Chocolate Cake 03",
        ctg: "Chocolate",
        price: 230000,
        img: Cake1,
        rating: 4.3,
        reviews: 100,
    },
    {
        title: "Chocolate Cake 04",
        ctg: "Chocolate",
        price: 280000,
        img: Cake1,
        rating: 4.7,
        reviews: 180,
    },
    {
        title: "Chocolate Cake 05",
        ctg: "Chocolate",
        price: 260000,
        img: Cake1,
        rating: 4.6,
        reviews: 160,
    },
    {
        title: "Chocolate Cake 06",
        ctg: "Chocolate",
        price: 240000,
        img: Cake1,
        rating: 4.4,
        reviews: 140,
    },
    {
        title: "Chocolate Cake 07",
        ctg: "Chocolate",
        price: 255000,
        img: Cake1,
        rating: 4.2,
        reviews: 110,
    },
    {
        title: "Chocolate Cake 08",
        ctg: "Chocolate",
        price: 265000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Chocolate Cake 09",
        ctg: "Chocolate",
        price: 245000,
        img: Cake1,
        rating: 4.1,
        reviews: 130,
    },
    {
        title: "Chocolate Cake 10",
        ctg: "Chocolate",
        price: 275000,
        img: Cake1,
        rating: 4.7,
        reviews: 170,
    },

    // Vanilla cakes
    {
        title: "Vanilla Cake 01",
        ctg: "Vanilla",
        price: 220000,
        img: Cake1,
        rating: 4.5,
        reviews: 120,
    },
    {
        title: "Vanilla Cake 02",
        ctg: "Vanilla",
        price: 240000,
        img: Cake1,
        rating: 4.3,
        reviews: 100,
    },
    {
        title: "Vanilla Cake 03",
        ctg: "Vanilla",
        price: 210000,
        img: Cake1,
        rating: 4.6,
        reviews: 130,
    },
    {
        title: "Vanilla Cake 04",
        ctg: "Vanilla",
        price: 230000,
        img: Cake1,
        rating: 4.7,
        reviews: 150,
    },
    {
        title: "Vanilla Cake 05",
        ctg: "Vanilla",
        price: 200000,
        img: Cake1,
        rating: 4.4,
        reviews: 110,
    },
    {
        title: "Vanilla Cake 06",
        ctg: "Vanilla",
        price: 215000,
        img: Cake1,
        rating: 4.8,
        reviews: 170,
    },
    {
        title: "Vanilla Cake 07",
        ctg: "Vanilla",
        price: 225000,
        img: Cake1,
        rating: 4.2,
        reviews: 90,
    },
    {
        title: "Vanilla Cake 08",
        ctg: "Vanilla",
        price: 235000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Vanilla Cake 09",
        ctg: "Vanilla",
        price: 205000,
        img: Cake1,
        rating: 4.1,
        reviews: 130,
    },
    {
        title: "Vanilla Cake 10",
        ctg: "Vanilla",
        price: 255000,
        img: Cake1,
        rating: 4.7,
        reviews: 160,
    },

    // Strawberry cakes
    {
        title: "Strawberry Cake 01",
        ctg: "Strawberry",
        price: 270000,
        img: Cake1,
        rating: 4.3,
        reviews: 100,
    },
    {
        title: "Strawberry Cake 02",
        ctg: "Strawberry",
        price: 250000,
        img: Cake1,
        rating: 4.8,
        reviews: 150,
    },
    {
        title: "Strawberry Cake 03",
        ctg: "Strawberry",
        price: 290000,
        img: Cake1,
        rating: 4.2,
        reviews: 110,
    },
    {
        title: "Strawberry Cake 04",
        ctg: "Strawberry",
        price: 260000,
        img: Cake1,
        rating: 4.5,
        reviews: 120,
    },
    {
        title: "Strawberry Cake 05",
        ctg: "Strawberry",
        price: 280000,
        img: Cake1,
        rating: 4.6,
        reviews: 130,
    },
    {
        title: "Strawberry Cake 06",
        ctg: "Strawberry",
        price: 245000,
        img: Cake1,
        rating: 4.4,
        reviews: 140,
    },
    {
        title: "Strawberry Cake 07",
        ctg: "Strawberry",
        price: 255000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Strawberry Cake 08",
        ctg: "Strawberry",
        price: 235000,
        img: Cake1,
        rating: 4.1,
        reviews: 80,
    },
    {
        title: "Strawberry Cake 09",
        ctg: "Strawberry",
        price: 265000,
        img: Cake1,
        rating: 4.7,
        reviews: 160,
    },
    {
        title: "Strawberry Cake 10",
        ctg: "Strawberry",
        price: 300000,
        img: Cake1,
        rating: 4.8,
        reviews: 170,
    },

    // Red Velvet cakes
    {
        title: "Red Velvet Cake 01",
        ctg: "Red Velvet",
        price: 300000,
        img: Cake1,
        rating: 4.7,
        reviews: 180,
    },
    {
        title: "Red Velvet Cake 02",
        ctg: "Red Velvet",
        price: 320000,
        img: Cake1,
        rating: 4.6,
        reviews: 170,
    },
    {
        title: "Red Velvet Cake 03",
        ctg: "Red Velvet",
        price: 280000,
        img: Cake1,
        rating: 4.8,
        reviews: 190,
    },
    {
        title: "Red Velvet Cake 04",
        ctg: "Red Velvet",
        price: 290000,
        img: Cake1,
        rating: 4.5,
        reviews: 160,
    },
    {
        title: "Red Velvet Cake 05",
        ctg: "Red Velvet",
        price: 310000,
        img: Cake1,
        rating: 4.4,
        reviews: 150,
    },
    {
        title: "Red Velvet Cake 06",
        ctg: "Red Velvet",
        price: 330000,
        img: Cake1,
        rating: 4.9,
        reviews: 200,
    },
    {
        title: "Red Velvet Cake 07",
        ctg: "Red Velvet",
        price: 270000,
        img: Cake1,
        rating: 4.3,
        reviews: 120,
    },
    {
        title: "Red Velvet Cake 08",
        ctg: "Red Velvet",
        price: 325000,
        img: Cake1,
        rating: 4.2,
        reviews: 110,
    },
    {
        title: "Red Velvet Cake 09",
        ctg: "Red Velvet",
        price: 295000,
        img: Cake1,
        rating: 4.1,
        reviews: 100,
    },
    {
        title: "Red Velvet Cake 10",
        ctg: "Red Velvet",
        price: 315000,
        img: Cake1,
        rating: 4.0,
        reviews: 90,
    },

    // Lemon cakes
    {
        title: "Lemon Cake 01",
        ctg: "Lemon",
        price: 280000,
        img: Cake1,
        rating: 4.6,
        reviews: 160,
    },
    {
        title: "Lemon Cake 02",
        ctg: "Lemon",
        price: 300000,
        img: Cake1,
        rating: 4.5,
        reviews: 150,
    },
    {
        title: "Lemon Cake 03",
        ctg: "Lemon",
        price: 260000,
        img: Cake1,
        rating: 4.4,
        reviews: 140,
    },
    {
        title: "Lemon Cake 04",
        ctg: "Lemon",
        price: 270000,
        img: Cake1,
        rating: 4.8,
        reviews: 170,
    },
    {
        title: "Lemon Cake 05",
        ctg: "Lemon",
        price: 290000,
        img: Cake1,
        rating: 4.3,
        reviews: 120,
    },
    {
        title: "Lemon Cake 06",
        ctg: "Lemon",
        price: 250000,
        img: Cake1,
        rating: 4.7,
        reviews: 180,
    },
    {
        title: "Lemon Cake 07",
        ctg: "Lemon",
        price: 265000,
        img: Cake1,
        rating: 4.2,
        reviews: 110,
    },
    {
        title: "Lemon Cake 08",
        ctg: "Lemon",
        price: 255000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Lemon Cake 09",
        ctg: "Lemon",
        price: 245000,
        img: Cake1,
        rating: 4.1,
        reviews: 100,
    },
    {
        title: "Lemon Cake 10",
        ctg: "Lemon",
        price: 275000,
        img: Cake1,
        rating: 4.0,
        reviews: 90,
    },

    // Caramel cakes
    {
        title: "Caramel Cake 01",
        ctg: "Caramel",
        price: 260000,
        img: Cake1,
        rating: 4.4,
        reviews: 140,
    },
    {
        title: "Caramel Cake 02",
        ctg: "Caramel",
        price: 280000,
        img: Cake1,
        rating: 4.7,
        reviews: 170,
    },
    {
        title: "Caramel Cake 03",
        ctg: "Caramel",
        price: 240000,
        img: Cake1,
        rating: 4.2,
        reviews: 110,
    },
    {
        title: "Caramel Cake 04",
        ctg: "Caramel",
        price: 250000,
        img: Cake1,
        rating: 4.6,
        reviews: 130,
    },
    {
        title: "Caramel Cake 05",
        ctg: "Caramel",
        price: 230000,
        img: Cake1,
        rating: 4.8,
        reviews: 150,
    },
    {
        title: "Caramel Cake 06",
        ctg: "Caramel",
        price: 245000,
        img: Cake1,
        rating: 4.5,
        reviews: 120,
    },
    {
        title: "Caramel Cake 07",
        ctg: "Caramel",
        price: 255000,
        img: Cake1,
        rating: 4.1,
        reviews: 100,
    },
    {
        title: "Caramel Cake 08",
        ctg: "Caramel",
        price: 265000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Caramel Cake 09",
        ctg: "Caramel",
        price: 235000,
        img: Cake1,
        rating: 4.3,
        reviews: 160,
    },
    {
        title: "Caramel Cake 10",
        ctg: "Caramel",
        price: 275000,
        img: Cake1,
        rating: 4.0,
        reviews: 80,
    },
    // Blueberry cakes
    {
        title: "Blueberry Cake 01",
        ctg: "Blueberry",
        price: 290000,
        img: Cake1,
        rating: 4.5,
        reviews: 110,
    },
    {
        title: "Blueberry Cake 02",
        ctg: "Blueberry",
        price: 310000,
        img: Cake1,
        rating: 4.7,
        reviews: 130,
    },
    {
        title: "Blueberry Cake 03",
        ctg: "Blueberry",
        price: 280000,
        img: Cake1,
        rating: 4.8,
        reviews: 150,
    },
    {
        title: "Blueberry Cake 04",
        ctg: "Blueberry",
        price: 300000,
        img: Cake1,
        rating: 4.6,
        reviews: 140,
    },
    {
        title: "Blueberry Cake 05",
        ctg: "Blueberry",
        price: 320000,
        img: Cake1,
        rating: 4.4,
        reviews: 120,
    },
    {
        title: "Blueberry Cake 06",
        ctg: "Blueberry",
        price: 290000,
        img: Cake1,
        rating: 4.9,
        reviews: 160,
    },
    {
        title: "Blueberry Cake 07",
        ctg: "Blueberry",
        price: 280000,
        img: Cake1,
        rating: 4.2,
        reviews: 100,
    },
    {
        title: "Blueberry Cake 08",
        ctg: "Blueberry",
        price: 300000,
        img: Cake1,
        rating: 4.1,
        reviews: 90,
    },
    {
        title: "Blueberry Cake 09",
        ctg: "Blueberry",
        price: 310000,
        img: Cake1,
        rating: 4.3,
        reviews: 110,
    },
    {
        title: "Blueberry Cake 10",
        ctg: "Blueberry",
        price: 320000,
        img: Cake1,
        rating: 4.7,
        reviews: 130,
    },

    // Coconut cakes
    {
        title: "Coconut Cake 01",
        ctg: "Coconut",
        price: 310000,
        img: Cake1,
        rating: 4.2,
        reviews: 120,
    },
    {
        title: "Coconut Cake 02",
        ctg: "Coconut",
        price: 330000,
        img: Cake1,
        rating: 4.5,
        reviews: 150,
    },
    {
        title: "Coconut Cake 03",
        ctg: "Coconut",
        price: 300000,
        img: Cake1,
        rating: 4.3,
        reviews: 130,
    },
    {
        title: "Coconut Cake 04",
        ctg: "Coconut",
        price: 320000,
        img: Cake1,
        rating: 4.6,
        reviews: 140,
    },
    {
        title: "Coconut Cake 05",
        ctg: "Coconut",
        price: 310000,
        img: Cake1,
        rating: 4.8,
        reviews: 160,
    },
    {
        title: "Coconut Cake 06",
        ctg: "Coconut",
        price: 330000,
        img: Cake1,
        rating: 4.4,
        reviews: 140,
    },
    {
        title: "Coconut Cake 07",
        ctg: "Coconut",
        price: 340000,
        img: Cake1,
        rating: 4.7,
        reviews: 170,
    },
    {
        title: "Coconut Cake 08",
        ctg: "Coconut",
        price: 320000,
        img: Cake1,
        rating: 4.9,
        reviews: 180,
    },
    {
        title: "Coconut Cake 09",
        ctg: "Coconut",
        price: 330000,
        img: Cake1,
        rating: 4.1,
        reviews: 110,
    },
    {
        title: "Coconut Cake 10",
        ctg: "Coconut",
        price: 340000,
        img: Cake1,
        rating: 4.0,
        reviews: 100,
    },

    // Pineapple cakes
    {
        title: "Pineapple Cake 01",
        ctg: "Pineapple",
        price: 260000,
        img: Cake1,
        rating: 4.6,
        reviews: 140,
    },
    {
        title: "Pineapple Cake 02",
        ctg: "Pineapple",
        price: 280000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Pineapple Cake 03",
        ctg: "Pineapple",
        price: 250000,
        img: Cake1,
        rating: 4.5,
        reviews: 130,
    },
    {
        title: "Pineapple Cake 04",
        ctg: "Pineapple",
        price: 270000,
        img: Cake1,
        rating: 4.7,
        reviews: 150,
    },
    {
        title: "Pineapple Cake 05",
        ctg: "Pineapple",
        price: 290000,
        img: Cake1,
        rating: 4.8,
        reviews: 160,
    },
    {
        title: "Pineapple Cake 06",
        ctg: "Pineapple",
        price: 255000,
        img: Cake1,
        rating: 4.4,
        reviews: 120,
    },
    {
        title: "Pineapple Cake 07",
        ctg: "Pineapple",
        price: 265000,
        img: Cake1,
        rating: 4.2,
        reviews: 110,
    },
    {
        title: "Pineapple Cake 08",
        ctg: "Pineapple",
        price: 275000,
        img: Cake1,
        rating: 4.1,
        reviews: 100,
    },
    {
        title: "Pineapple Cake 09",
        ctg: "Pineapple",
        price: 285000,
        img: Cake1,
        rating: 4.3,
        reviews: 120,
    },
    {
        title: "Pineapple Cake 10",
        ctg: "Pineapple",
        price: 295000,
        img: Cake1,
        rating: 4.0,
        reviews: 90,
    },

    // Coffee cakes
    {
        title: "Coffee Cake 01",
        ctg: "Coffee",
        price: 300000,
        img: Cake1,
        rating: 4.8,
        reviews: 170,
    },
    {
        title: "Coffee Cake 02",
        ctg: "Coffee",
        price: 320000,
        img: Cake1,
        rating: 4.5,
        reviews: 150,
    },
    {
        title: "Coffee Cake 03",
        ctg: "Coffee",
        price: 280000,
        img: Cake1,
        rating: 4.3,
        reviews: 130,
    },
    {
        title: "Coffee Cake 04",
        ctg: "Coffee",
        price: 290000,
        img: Cake1,
        rating: 4.7,
        reviews: 160,
    },
    {
        title: "Coffee Cake 05",
        ctg: "Coffee",
        price: 310000,
        img: Cake1,
        rating: 4.6,
        reviews: 140,
    },
    {
        title: "Coffee Cake 06",
        ctg: "Coffee",
        price: 280000,
        img: Cake1,
        rating: 4.4,
        reviews: 120,
    },
    {
        title: "Coffee Cake 07",
        ctg: "Coffee",
        price: 290000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Coffee Cake 08",
        ctg: "Coffee",
        price: 300000,
        img: Cake1,
        rating: 4.2,
        reviews: 100,
    },
    {
        title: "Coffee Cake 09",
        ctg: "Coffee",
        price: 310000,
        img: Cake1,
        rating: 4.1,
        reviews: 90,
    },
    {
        title: "Coffee Cake 10",
        ctg: "Coffee",
        price: 320000,
        img: Cake1,
        rating: 4.0,
        reviews: 80,
    },

    // Hazelnut cakes
    {
        title: "Hazelnut Cake 01",
        ctg: "Hazelnut",
        price: 280000,
        img: Cake1,
        rating: 4.7,
        reviews: 160,
    },
    {
        title: "Hazelnut Cake 02",
        ctg: "Hazelnut",
        price: 300000,
        img: Cake1,
        rating: 4.9,
        reviews: 190,
    },
    {
        title: "Hazelnut Cake 03",
        ctg: "Hazelnut",
        price: 270000,
        img: Cake1,
        rating: 4.6,
        reviews: 150,
    },
    {
        title: "Hazelnut Cake 04",
        ctg: "Hazelnut",
        price: 290000,
        img: Cake1,
        rating: 4.8,
        reviews: 170,
    },
    {
        title: "Hazelnut Cake 05",
        ctg: "Hazelnut",
        price: 310000,
        img: Cake1,
        rating: 4.5,
        reviews: 130,
    },
    {
        title: "Hazelnut Cake 06",
        ctg: "Hazelnut",
        price: 280000,
        img: Cake1,
        rating: 4.3,
        reviews: 110,
    },
    {
        title: "Hazelnut Cake 07",
        ctg: "Hazelnut",
        price: 290000,
        img: Cake1,
        rating: 4.2,
        reviews: 100,
    },
    {
        title: "Hazelnut Cake 08",
        ctg: "Hazelnut",
        price: 300000,
        img: Cake1,
        rating: 4.1,
        reviews: 90,
    },
    {
        title: "Hazelnut Cake 09",
        ctg: "Hazelnut",
        price: 310000,
        img: Cake1,
        rating: 4.4,
        reviews: 120,
    },
    {
        title: "Hazelnut Cake 10",
        ctg: "Hazelnut",
        price: 320000,
        img: Cake1,
        rating: 4.0,
        reviews: 80,
    },
];